### ISSUE TITLE
Bootstrap dropdown-menu KO

### ISSUE THREAD

**Issue by pascoual** [JackAdams/meteor-editable-text-wysiwyg#1]
When we add editable-text-wysiwyg to our project, all dropdown-menus are ko.
## 

Pascoual

**Comment by JackAdams** [comment]
That's strange. The `babrahams:editable-text-wysiwyg` package by itself should do nothing.  The package to use is `babrahams:editable-text-wysiwyg-bootstrap-3`, which does have a dependency on `ian:bootstrap-3`.  I imagine the inclusion of this package is what's causing the problem.

If you could put a minimal repro on meteorpad.com, I could take a closer look.

**Comment by pascoual** [comment]
You're right :). Just made a PR on babrahams:editable-text-wysiwyg-bootstrap-3.

Thanks a lot.
Pascoual
